name: Publish packages
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.8.0
          registry-url: "https://npm.pkg.github.com"
      - name: Install
        run: npm install
      - name: Bootstrap
        run: npm run lerna:bootstrap
      - name: Build
        run: npm run build
      - name: Git status
        run: git status
      - name: Publish to npm registry
        run: |
          echo "@umich-lib:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm run lerna:publish-dev
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
