name: Development CSS deploy
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: "https://npm.pkg.github.com"
      - name: Install
        run: npm install
      - name: Lerna bootstrap
        run: npm run lerna:bootstrap
      - name: Build
        run: npm run build
      - name: Deploy dev CSS
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          build_dir: packages/css/dist
