# This is a basic workflow to help you get started with Actions

name: Development CSS deploy

# Controls when the action will run.
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
      - name: Install dependencies
        run: npm install
      - name: Lerna bootstrap
        run: npm run lerna:bootstrap
      - name: Build Design System
        run: npm run build
      - name: Deploy DEV CSS
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          build_dir: packages/css/dist
