name: Publish packages
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  publish-dev-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.8.0
      - name: Install
        run: npm install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Bootstrap
        run: npm run lerna:bootstrap
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build
        run: npm run build
      - name: Git status
        run: git status
      - name: Publish to npm registry
        run: |
          npm run lerna:publish-dev
